name: 6.1.118-LYRA-S-Tkocean

env:
  TZ: Asia/Shanghai
  ANDROID_VERSION: 'android14'
  KERNEL_VERSION: '6.1'
  KERNEL_NAME: 'android14-11-o-gca13bffobf09'

on:
  workflow_dispatch:
    inputs:
      bbr_enable:
        description: 'Enable BBR algorithm'
        required: false
        type: choice
        default: 'false'
        options:
          - 'false'
          - 'true'
          - 'default'
      lz4_enable:
        description: 'Install Patch'
        required: true
        type: boolean
        default: 'true'
      better_net:
        description: 'Enable extended configuration'
        required: true
        type: boolean
        default: 'true'
      ssg_enable:
        description: 'Enable Samsung SSG IO scheduler'
        required: true
        type: boolean
        default: 'true'
      rekernel_enable:
        description: 'Enable Re-Kernel support'
        required: true
        type: boolean
        default: 'false'
      baseband_guard:
        description: 'Enable kernel-level baseband protection'
        required: true
        type: boolean
        default: 'false'
      ccache_debug:
        description: 'Upload Ccache debug logs'
        required: true
        type: boolean
        default: 'false'
      kernel_suffix:
        description: 'Kernel suffix'
        required: false
        type: string
        default: 'LYRA-S-Tkocean'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      ksuver: ${{ steps.ksu_version.outputs.ksuver }}
    steps:
      - name: Install dependencies + initialize source repo and llvm-Clang20 toolchain
        run: |
          rm -rf kernel_workspace
          mkdir kernel_workspace
          cd kernel_workspace

          sudo apt-mark hold firefox &&
          sudo apt-mark hold libc-bin &&
          sudo apt purge man-db &&
          sudo rm -rf /var/lib/man-db/auto-update &&
          sudo apt update &&
          sudo apt-get install -y --no-install-recommends binutils python-is-python3 libssl-dev libelf-dev ccache &

          aria2c -s16 -x16 -k1M https://github.com/cctv18/android_kernel_common_oneplus_sm8650/archive/refs/heads/oneplus/sm8650_v_15.0.0_oneplus12_6.1.118.zip -o common.zip &&
          unzip -q common.zip &&
          mv "android_kernel_common_oneplus_sm8650-oneplus-sm8650_v_15.0.0_oneplus12_6.1.118" common &&
          rm -rf common.zip &

          mkdir -p clang20 &&
          aria2c -s16 -x16 -k1M https://github.com/cctv18/oneplus_sm8650_toolchain/releases/download/LLVM-Clang20-r547379/clang-r547379.zip -o clang.zip &&
          unzip -q clang.zip -d clang20 &&
          rm -rf clang.zip &

          aria2c -s16 -x16 -k1M https://github.com/cctv18/oneplus_sm8650_toolchain/releases/download/LLVM-Clang20-r547379/build-tools.zip -o build-tools.zip &&
          unzip -q build-tools.zip &&
          rm -rf build-tools.zip &

          wait
          rm common/android/abi_gki_protected_exports_* || true
          for f in common/scripts/setlocalversion; do
            sed -i 's/ -dirty//g' "$f"
            sed -i '$i res=$(echo "$res" | sed '\''s/-dirty//g'\'')' "$f"
          done

      - name: Configure ccache directory
        run: |
          echo "CCACHE_DIR=$HOME/.ccache_6.1.118" >> $GITHUB_ENV
          echo "CCACHE_MAXSIZE=3G" >> $GITHUB_ENV
          df -h
          echo "Current kernel version: 6.1.118"

      - name: Load ccache for current kernel version
        uses: actions/cache@v4
        id: ccache-restore
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-neov3-6.1.118-${{ runner.os }}-main
          restore-keys: |
            ccache-neov3-6.1.118-${{ runner.os }}-
            ccache-neov3-6.1.118-

      - name: Initialize and configure ccache
        run: |
          export CCACHE_COMPILERCHECK="none"
          export CCACHE_BASEDIR="${{ github.workspace }}"
          export CCACHE_NOHASHDIR="true"
          export CCACHE_HARDLINK="true"
          export CCACHE_DIR="${{ env.CCACHE_DIR }}"
          export CCACHE_MAXSIZE="${{ env.CCACHE_MAXSIZE }}"

          mkdir -p "$CCACHE_DIR"
          echo "Setting ccache size to: $CCACHE_MAXSIZE"
          ccache -M "$CCACHE_MAXSIZE"
          ccache -o compression=true

          echo "Initial ccache status:"
          ccache -s

          if [ "${{ steps.ccache-restore.outputs.cache-hit }}" == 'true' ]; then
            echo "Cache hit details:"
            ccache -sv
          fi

      - name: Apply lz4 1.10.0 & zstd 1.5.7 patches
        if: inputs.lz4_enable
        run: |
          cd kernel_workspace
          git clone https://github.com/cctv18/oppo_oplus_realme_sm8650.git
          cp ./oppo_oplus_realme_sm8650/zram_patch/001-lz4.patch ./common/
          cp ./oppo_oplus_realme_sm8650/zram_patch/lz4armv8.S ./common/lib
          cp ./oppo_oplus_realme_sm8650/zram_patch/002-zstd.patch ./common/
          cd ./common
          git apply -p1 < 001-lz4.patch || true
          patch -p1 < 002-zstd.patch || true

      - name: Enable enhanced network configuration
        if: inputs.better_net
        run: |
          cd kernel_workspace
          {
            echo "CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE=y"
            echo "CONFIG_JUMP_LABEL=y"
            echo "CONFIG_TRANSPARENT_HUGEPAGE=y"
            echo "CONFIG_HZ_300=y"
            echo "CONFIG_BPF_STREAM_PARSER=y"
            echo "CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y"
            echo "CONFIG_NETFILTER_XT_SET=y"
            echo "CONFIG_IP_SET=y"
            echo "CONFIG_IP_SET_MAX=65534"
            echo "CONFIG_IP_SET_BITMAP_IP=y"
            echo "CONFIG_IP_SET_BITMAP_IPMAC=y"
            echo "CONFIG_IP_SET_BITMAP_PORT=y"
            echo "CONFIG_IP_SET_HASH_IP=y"
            echo "CONFIG_IP_SET_HASH_IPMARK=y"
            echo "CONFIG_IP_SET_HASH_IPPORT=y"
            echo "CONFIG_IP_SET_HASH_IPPORTIP=y"
            echo "CONFIG_IP_SET_HASH_IPPORTNET=y"
            echo "CONFIG_IP_SET_HASH_IPMAC=y"
            echo "CONFIG_IP_SET_HASH_MAC=y"
            echo "CONFIG_IP_SET_HASH_NETPORTNET=y"
            echo "CONFIG_IP_SET_HASH_NET=y"
            echo "CONFIG_IP_SET_HASH_NETNET=y"
            echo "CONFIG_IP_SET_HASH_NETPORT=y"
            echo "CONFIG_IP_SET_HASH_NETIFACE=y"
            echo "CONFIG_IP_SET_LIST_SET=y"
            echo "CONFIG_IP6_NF_NAT=y"
            echo "CONFIG_IP6_NF_TARGET_MASQUERADE=y"
            echo "CONFIG_DEBUG_KERNEL=n"
            echo "CONFIG_DEBUG_INFO=n"
            echo "CONFIG_KGDB=n"
            echo "CONFIG_KDB=n"
            echo "CONFIG_DYNAMIC_DEBUG=n"
            echo "CONFIG_KASAN=n"
            echo "CONFIG_KMEMLEAK=n"
            echo "CONFIG_UBSAN=n"
            echo "CONFIG_DEBUG_FS=n"
            echo "CONFIG_KPROBES=n"
            echo "CONFIG_NO_HZ_FULL=n"
            echo "CONFIG_CORE_SMALL=n"
            echo "CONFIG_NET_SMALL=n"
            echo "CONFIG_INIT_ON_ALLOC_DEFAULT_ON=n"
            echo "CONFIG_INIT_ON_FREE_DEFAULT_ON=n"
          } >> ./common/arch/arm64/configs/gki_defconfig
          sed -i 's/check_defconfig//' ./common/build.config.gki
          echo "CONFIG_HEADERS_INSTALL=n" >> ./common/arch/arm64/configs/gki_defconfig
          cd common
          wget https://github.com/cctv18/oppo_oplus_realme_sm8650/raw/refs/heads/main/other_patch/config.patch
          patch -p1 -F 3 < config.patch || true
          curl -LSs "https://raw.githubusercontent.com/Tkocean/Lyra/refs/heads/main/lib/unicode.patch" | patch -p1 --forward

      - name: Add BBR and other congestion control algorithms
        run: |
          if [[ "${{ github.event.inputs.bbr_enable }}" != "false" ]]; then
            cd kernel_workspace
            echo "CONFIG_TCP_CONG_ADVANCED=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_TCP_CONG_BBR=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_TCP_CONG_CUBIC=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_TCP_CONG_VEGAS=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_TCP_CONG_NV=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_TCP_CONG_WESTWOOD=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_TCP_CONG_HTCP=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_TCP_CONG_BRUTAL=y" >> ./common/arch/arm64/configs/gki_defconfig
            if [[ "${{ github.event.inputs.bbr_enable }}" == "default" ]]; then
              echo "CONFIG_DEFAULT_TCP_CONG=bbr" >> ./common/arch/arm64/configs/gki_defconfig
            else
              echo "CONFIG_DEFAULT_TCP_CONG=cubic" >> ./common/arch/arm64/configs/gki_defconfig
            fi
          fi

      - name: Enable Samsung SSG IO scheduler
        if: inputs.ssg_enable
        run: |
          cd kernel_workspace
          echo "CONFIG_MQ_IOSCHED_SSG=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_MQ_IOSCHED_SSG_CGROUP=y" >> ./common/arch/arm64/configs/gki_defconfig

      - name: Enable Re-Kernel support
        if: inputs.rekernel_enable
        run: |
          cd kernel_workspace
          echo "CONFIG_REKERNEL=y" >> ./common/arch/arm64/configs/gki_defconfig

      - name: Enable kernel-level baseband protection
        if: inputs.baseband_guard
        run: |
          cd kernel_workspace
          echo "CONFIG_BBG=y" >> ./common/arch/arm64/configs/gki_defconfig
          cd ./common/security
          wget https://github.com/cctv18/Baseband-guard/archive/refs/heads/master.zip
          unzip -q master.zip
          mv "Baseband-guard-master" baseband-guard
          printf '\nobj-$(CONFIG_BBG) += baseband-guard/\n' >> ./Makefile
          sed -i '/^config LSM$/,/^help$/{ /^[[:space:]]*default/ { /baseband_guard/! s/lockdown/lockdown,baseband_guard/ } }' ./Kconfig
          awk '
          /endmenu/ { last_endmenu_line = NR }
          { lines[NR] = $0 }
          END {
            for (i=1; i<=NR; i++) {
              if (i == last_endmenu_line) {
                sub(/endmenu/, "", lines[i]);
                print lines[i] "source \"security/baseband-guard/Kconfig\""
                print ""
                print "endmenu"
              } else {
                  print lines[i]
              }
            }
          }
          ' ./Kconfig > Kconfig.tmp && mv Kconfig.tmp ./Kconfig
          sed -i 's/selinuxfs.o //g' "./selinux/Makefile"
          sed -i 's/hooks.o //g' "./selinux/Makefile"
          cat "./baseband-guard/sepatch.txt" >> "./selinux/Makefile"

      - name: Set kernel version suffix
        run: |
          cd kernel_workspace
          echo "Replacing kernel version suffix..."
          if [[ -n "${{ github.event.inputs.kernel_suffix }}" ]]; then
            echo "Current kernel suffix: ${{ github.event.inputs.kernel_suffix }}"
            for f in ./common/scripts/setlocalversion; do
              sed -i "\$s|echo \"\\\$res\"|echo \"-${{ github.event.inputs.kernel_suffix }}\"|" "$f"
            done
          else
            echo "Current kernel suffix: ${{
              env.KERNEL_NAME }}"
            for f in ./common/scripts/setlocalversion; do
              sed -i "\$s|echo \"\\\$res\"|echo \"-${{ env.KERNEL_NAME }}\"|" "$f"
            done
          fi

      - name: Build kernel
        run: |
          WORKDIR="$(pwd)"
          export PATH="/usr/lib/ccache:$PATH"
          export PATH="$WORKDIR/kernel_workspace/clang20/bin:$PATH"
          export PATH="$WORKDIR/kernel_workspace/build-tools/bin:$PATH"
          CLANG_DIR="$WORKDIR/kernel_workspace/clang20/bin"
          CLANG_VERSION="$($CLANG_DIR/clang --version | head -n 1)"
          LLD_VERSION="$($CLANG_DIR/ld.lld --version | head -n 1)"
          echo "Compiler info:"
          echo "Clang version: $CLANG_VERSION"
          echo "LLD version: $LLD_VERSION"
          pahole_version=$(pahole --version 2>/dev/null | head -n1); [ -z "$pahole_version" ] && echo "pahole version: not installed" || echo "pahole version: $pahole_version"

          export CCACHE_LOGFILE="${{ github.workspace }}/kernel_workspace/ccache.log"
          export CCACHE_COMPILERCHECK="none"
          export CCACHE_BASEDIR="${{ github.workspace }}"
          export CCACHE_NOHASHDIR="true"
          export CCACHE_HARDLINK="true"
          export CCACHE_DIR="${{ env.CCACHE_DIR }}"
          export CCACHE_MAXSIZE="3G"
          echo "sloppiness = file_stat_matches,include_file_ctime,include_file_mtime,pch_defines,file_macro,time_macros" >> "$CCACHE_DIR/ccache.conf"

          cd kernel_workspace/common
          wget https://github.com/cctv18/oppo_oplus_realme_sm8650/raw/refs/heads/main/lib/libfakestat.so
          wget https://github.com/cctv18/oppo_oplus_realme_sm8650/raw/refs/heads/main/lib/libfaketimeMT.so
          chmod 777 ./*.so
          export FAKESTAT="2025-05-25 12:00:00"
          export FAKETIME="@2025-05-25 13:00:00"
          echo "FAKESTAT=$FAKESTAT" >> $GITHUB_ENV
          echo "FAKETIME=$FAKETIME" >> $GITHUB_ENV
          SO_DIR=$(pwd)
          export PRELOAD_LIBS="$SO_DIR/libfakestat.so $SO_DIR/libfaketimeMT.so"
          echo '#!/bin/bash' > cc-wrapper
          echo 'export LD_PRELOAD="'$PRELOAD_LIBS'"' >> cc-wrapper
          echo 'export FAKESTAT="'$FAKESTAT'"' >> cc-wrapper
          echo 'export FAKETIME="'$FAKETIME'"' >> cc-wrapper
          echo 'ccache clang "$@"' >> cc-wrapper
          echo '#!/bin/bash' > ld-wrapper
          echo 'export LD_PRELOAD="'$PRELOAD_LIBS'"' >> ld-wrapper
          echo 'export FAKESTAT="'$FAKESTAT'"' >> ld-wrapper
          echo 'export FAKETIME="'$FAKETIME'"' >> ld-wrapper
          echo 'ld.lld "$@"' >> ld-wrapper
          echo "--- [Wrapper Test] Creating general time hijack test script ---"
          echo '#!/bin/bash' > test-wrapper.sh
          echo 'export LD_PRELOAD="'$PRELOAD_LIBS'"' >> test-wrapper.sh
          echo 'export FAKESTAT="'$FAKESTAT'"' >> test-wrapper.sh
          echo 'export FAKETIME="'$FAKETIME'"' >> test-wrapper.sh
          echo 'echo ">>> Wrapper environment check complete."' >> test-wrapper.sh
          echo 'exec "$@"' >> test-wrapper.sh
          chmod +x test-wrapper.sh
          echo "--- [Wrapper Test] Testing (date) command ---"
          ./test-wrapper.sh date
          echo "--- [Wrapper Test] Testing (stat) command ---"
          ./test-wrapper.sh stat ./Makefile
          echo "--- [Wrapper Test] Completed ---"
          chmod +x cc-wrapper ld-wrapper
          echo "--- Pre-build environment time: $(LD_PRELOAD=$PRELOAD_LIBS date) ---"
          echo "--- Pre-build file timestamps: ---"
          LD_PRELOAD=$PRELOAD_LIBS stat ./Makefile

          sudo rm -rf /usr/share/dotnet &
          sudo rm -rf /usr/local/lib/android &
          sudo rm -rf /opt/ghc &
          sudo rm -rf /opt/hostedtoolcache/CodeQL &
          make -j$(nproc --all) LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC="ccache clang" LD="ld.lld" HOSTLD=ld.lld O=out KCFLAGS+=-O2 KCFLAGS+=-Wno-error gki_defconfig &&
          make -j$(nproc --all) LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC="$(pwd)/cc-wrapper" LD="$(pwd)/ld-wrapper" HOSTLD=ld.lld O=out KCFLAGS+=-O2 KCFLAGS+=-Wno-error Image

          echo "--- Post-build environment time: $(LD_PRELOAD=$PRELOAD_LIBS date) ---"
          echo "--- Post-build file timestamps: ---"
          LD_PRELOAD=$PRELOAD_LIBS stat ./Makefile
          echo "Kernel build completed!"
          echo "ccache status:"
          ccache -s
          echo "Disk usage after build:"
          df -h

      - name: Clone AnyKernel3 and package
        run: |
          cd kernel_workspace
          git clone https://github.com/Tkocean/AnyKernel3 --depth=1
          rm -rf ./AnyKernel3/.git
          cd AnyKernel3
          cp ../common/out/arch/arm64/boot/Image ./Image
          if [[ ! -f ./Image ]]; then
            echo "Kernel image not found, build may have failed"
            exit 1
          fi
          if [[ -n "${{ github.event.inputs.kernel_suffix }}" ]]; then
            zip -r ../AnyKernel3_${{ github.event.inputs.kernel_suffix }}.zip ./*
          else
            zip -r ../AnyKernel3_${{ env.KERNEL_NAME }}.zip ./*
          fi

      - name: Upload Ccache debug log
        if: always() && inputs.ccache_debug
        uses: actions/upload-artifact@v4
        with:
          name: ccache-debug-log
          path: ${{ github.workspace }}/kernel_workspace/ccache.log

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kernel_ZIP_Artifacts
          path: ${{ github.workspace }}/kernel_workspace/AnyKernel*.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: read

    steps:
      - name: Download ZIP artifact
        uses: actions/download-artifact@v4
        with:
          name: Kernel_ZIP_Artifacts
          path: ./release_zips

      - name: Set environment variables
        run: |
          if [[ -n "${{ github.event.inputs.kernel_suffix }}" ]]; then
            FULL_VERSION=${{ format('{0}.118-{1}', env.KERNEL_VERSION, github.event.inputs.kernel_suffix) }}
            echo "FULL_VERSION=$FULL_VERSION" >> $GITHUB_ENV
            export FULL_VERSION=$FULL_VERSION
          else
            FULL_VERSION=${{ format('{0}.118-{1}', env.KERNEL_VERSION, env.KERNEL_NAME) }}
            echo "FULL_VERSION=$FULL_VERSION" >> $GITHUB_ENV
            export FULL_VERSION=$FULL_VERSION
          fi
          TIME="$(TZ='Asia/Shanghai' date +'%y%m%d%H%M')"
          TIME_FORM="$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          echo "TIME=$TIME" >> $GITHUB_ENV
          echo "TIME_FORM=$TIME_FORM" >> $GITHUB_ENV

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ env.TIME }}"
          name: "${{ env.FULL_VERSION }}"
          body: |
            - Kernel version: ${{ env.FULL_VERSION }}
            - Build time: ${{ env.TIME_FORM }}
            - Install Patch: ${{ github.event.inputs.lz4_enable }}
            - Enable extended configuration: ${{ github.event.inputs.better_net }}
            - BBR/Brutal congestion control algorithms support: ${{ github.event.inputs.bbr_enable }}
            - Samsung SSG I/O scheduler: ${{ github.event.inputs.ssg_enable }}
            - Re-Kernel support: ${{ github.event.inputs.rekernel_enable }}
            - Kernel-level baseband protection: ${{ github.event.inputs.baseband_guard }}
            - [HorizonKernelFlasher](https://github.com/libxzr/HorizonKernelFlasher/releases)
          draft: false
          prerelease: false
          files: |
            release_zips/AnyKernel3_*.zip









